version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://your_user:your_password@db:5432/your_db
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A your_project worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://your_user:your_password@db:5432/your_db
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A your_project beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://your_user:your_password@db:5432/your_db
      - REDIS_URL=redis://redis:6379/0

  bot:
    build: .
    command: python -m your_bot_module
    volumes:
      - .:/code
    depends_on:
      - web
    environment:
      - DATABASE_URL=postgres://your_user:your_password@db:5432/your_db
      - API_URL=http://web:8000/api/

volumes:
  postgres_data:
  redis_data: